language: node_js

services:
  - docker

node_js:
  - 8
  - 10

install:
  - travis_retry yarn
  - yarn add --dev coveralls

script:
  - yarn test --coverage --coverageReporters=text-lcov | coveralls

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - ls -la
        - yarn semantic-release
