language: node_js

services:
  - docker

node_js:
  - 10

install:
  - travis_retry yarn

jobs:
  include:
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - yarn test --coverage
    - stage: release
      node_js: lts/*
      script:
        - yarn semantic-release
