language: node_js

services:
  - docker

node_js:
  - 10

install:
  - travis_retry yarn
  - yarn add --dev coveralls

jobs:
  include:
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - yarn test --coverage --coverageReporters=text-lcov | coveralls
    - stage: build
      script:
        - yarn build
    - stage: release
      node_js: lts/*
      script:
        - yarn semantic-release
