language: node_js

services:
  - docker

node_js:
  - 10

# branches:
#   only:
#     - master

install:
  - travis_retry yarn

script:
  - yarn lint
  - yarn test --coverage

# after_success:
#   - npm run codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn semantic-release
