language: node_js

services:
  - docker

node_js:
  - 8
  - 10

install:
  - travis_retry yarn

jobs:
  include:
    - stage: build
      script:
        - yarn lint
        - yarn add --dev coveralls
        - yarn test --coverage --coverageReporters=text-lcov | coveralls
        - yarn build
    - stage: release
      node_js: lts/*
      script:
        - yarn semantic-release
